name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - main 

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update GitHub Stats
        uses: anuraghazra/github-readme-stats@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Puedes personalizar las opciones aquí
          # Ejemplo:
          show_icons: true
          theme: dark
          hide_border: true

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub stats"
